#! /usr/bin/env php
<?php
/**
 * Script to bootstrap the Cobweb manager command line tool.
 */
set_time_limit(0);
error_reporting(E_ALL);
define('COBWEB_DIRECTORY', realpath(dirname(__FILE__) . '/..'));
require_once dirname(__FILE__) . '/../core/cobweb_bootstrap.inc.php';
error_reporting(E_ALL);
require_once COBWEB_DIRECTORY . '/manager/cobweb_manager.class.php';
CobwebManager::run($_SERVER['argv']);
